version: '2'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vrmarket
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./volumes/proxy/certs:/etc/nginx/certs:ro
    network_mode: bridge

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen


  db:
    image: postgres:10
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
#    ports:
#      - 5432
#    volumes:
#      - odoo-db-data:/var/lib/postgresql/data/pgdata


  psycho:
    image: odoo:12.0
    container_name: psycho
    depends_on:
      - db
    ports:
      - 8070:8069
    tty: true
    stdin_open: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - odoo-psycho-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    environment:
      - VIRTUAL_HOST=katekalynovska.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8070, 8080
      - LETSENCRYPT_HOST=katekalynovska.com
      - LETSENCRYPT_EMAIL=kate.kalynovska@gmail.com

  vrmarket:
    image: odoo:12.0
    container_name: vrmarket
    depends_on:
      - db
    ports:
      - 8071:8069
    tty: true
    stdin_open: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - odoo-vrmarket-data:/var/lib/odoo      
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    environment:
      - VIRTUAL_HOST=vrmarket.com.ua
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8071, 8081
      - LETSENCRYPT_HOST=vrmarket.com.ua
      - LETSENCRYPT_EMAIL=smaystr@gmail.com
    

volumes:
  odoo-vrmarket-data:
  odoo-psycho-data:        
#  odoo-db-data:
